USE INSTA;

SELECT * FROM ACCOUNTS;

SELECT USERNAME FROM ACCOUNTS
WHERE POSTS>100;

#ORDER BY
SELECT * FROM ACCOUNTS 
WHERE POSTS>100 ORDER BY NAME;

SELECT * FROM ACCOUNTS 
WHERE POSTS>100 ORDER BY NAME DESC;

SELECT COUNT(USERNAME),COUNTRY FROM ACCOUNTS GROUP BY COUNTRY;
SELECT MAX(POSTS),MIN(POSTS) FROM ACCOUNTS;

SELECT MAX(POSTS),MIN(POSTS),COUNTRY FROM ACCOUNTS GROUP BY COUNTRY;

SELECT AVG(POSTS),SUM(POSTS),COUNTRY FROM ACCOUNTS GROUP BY COUNTRY;

#HAVING
SELECT COUNT(USERNAME),COUNTRY FROM ACCOUNTS GROUP BY COUNTRY
HAVING COUNT(USERNAME)>1;


