USE INSTA;
CREATE TABLE ACCOUNTS1(USERNAME VARCHAR(20),LIKES int,POSTS INT);

INSERT INTO ACCOUNTS1 values ('sam_1',10,20),
('john_2',20,7),
('Rupesh_1',6,10),
('Dheeraj_2',20,3),
('Maruthi_1',9,7),
('Maruthi_1',9,7),
('david_1',1,10);

CREATE TABLE LIKES1(USERNAME VARCHAR(20),LIKES int,POSTS INT);
DROP TABLE LIKES1;
INSERT INTO LIKES1 VALUES ('john_2',20,7),
('Rupesh_1',6,10),
('BALA_1',2,3),
('Hemanth_2',9,10),
('Giri_2',10,8);

SELECT * FROM ACCOUNTS1;

SELECT * FROM LIKES1;

#UNION
SELECT * FROM ACCOUNTS1
UNION
SELECT * FROM LIKES1;

#UNION ALL
SELECT * FROM ACCOUNTS1
UNION ALL
SELECT * FROM LIKES1;

#INTERSECT
SELECT * FROM ACCOUNTS1
INTERSECT
SELECT * FROM LIKES1;

#EXCEPT
SELECT * FROM ACCOUNTS1
EXCEPT
SELECT * FROM LIKES1;

#SUBQUERY
SELECT (SELECT USERNAME FROM LIKES1 WHERE ACCOUNTS1.USERNAME=LIKES1.USERNAME)
FROM ACCOUNTS1
WHERE LIKES>10;





