#Data Definition Language
CREATE DATABASE NIT;

USE NIT;
#CREATE
CREATE TABLE COURSES(COURSEID VARCHAR(255),BRANCH CHAR(50));

SELECT * FROM COURSES;

INSERT into COURSES VALUES("CS01","AIML"),
("CS02","DS"),
("CS03","ECE"),
("CS04","MECH"),
("CS05","CIVIL"),
("CS06","BT");

#ALTER
ALTER TABLE COURSES ADD COLUMN PROOFESOR VARCHAR(255);
ALTER TABLE COURSES MODIFY PROOFESOR INT;
ALTER TABLE COURSES DROP PROOFESOR;
ALTER TABLE COURSES RENAME COLUMN BRANCH TO COURSE;

#DROP
DROP TABLE COURSES;

#TURNCATE
TRUNCATE TABLE COURSES;