CREATE DATABASE SASI;
USE SASI;
CREATE TABLE STUDENTS(ID INT PRIMARY KEY,NAME CHAR(255),COURSE CHAR(255));

INSERT INTO STUDENTS VALUES(1,"SAM","CSE"),
(2,"MARUTHI","ECE"),
(3,"RUPESH","ML"),
(4,"VINAY","MECH");

SELECT * FROM STUDENTS;



CREATE TABLE COURSES(ID INT PRIMARY KEY,BRANCH VARCHAR(255));

INSERT INTO COURSES VALUES(1,"AIML"),
(2,"CSE"),
(3,"ECE"),
(4,"MECH"),
(5,"VLSI");

SELECT * FROM COURSES;


CREATE TABLE STUDENTS1(ID INT ,NAME CHAR(255),COURSEID  VARCHAR(255),FOREIGN KEY (ID) REFERENCES COURSES(ID));

INSERT INTO STUDENTS1 VALUES(1,"SAM","CS41"),
(2,"MARUTHI","EC42"),
(3,"RUPESH","ML40"),
(4,"VINAY","ME43");

SELECT * FROM STUDENTS1;


DROP TABLE STUDENTS3;


CREATE TABLE STUDENTS2(ID INT UNIQUE,NAME CHAR(255),COURSE CHAR(255));

INSERT INTO STUDENTS2 VALUES(1,"SAM","CSE"),
(2,"MARUTHI","ECE"),
(3,"RUPESH","ML"),
(4,"VINAY","MECH");

INSERT INTO STUDENTS2(NAME,COURSE) VALUES("DHEERAJ","CHEMICAL");

SELECT * FROM STUDENTS2;


CREATE TABLE ROLLNUMBER(YOF INT,CLG CHAR(255),COURSE VARCHAR(255),PRIMARY KEY(YOF,CLG,COURSE));

INSERT INTO ROLLNUMBER VALUES(18,"JNTU","AIML"),
(19,"NIT","CSE"),
(20,"IIT","AIML");

SELECT *,CONCAT(YOF,CLG,COURSE) AS ROLL FROM ROLLNUMBER;

CREATE TABLE STUDENTS3(ID INT AUTO_INCREMENT PRIMARY KEY,NAME CHAR(255),BRANCH CHAR(255));

INSERT INTO STUDENTS3(NAME,BRANCH) VALUES("SAM","CSE"),
("MARUTHI","ECE"),
("RUPESH","AIML");

SELECT * FROM STUDENTS3;





